name: Alex

on:
  pull_request:
    types:
      - labeled
      - closed

jobs:
  debug-branch-name:
    runs-on: ubuntu-latest
    steps:
      # Printout GHAction variablesdd
      - name: Print GHAction variables
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
          echo "github.event.number: ${{ github.event.number }}"

